CREATE TABLE Owner (
    OwnerID INT PRIMARY KEY IDENTITY(1,1),
    OwnerName NVARCHAR(100) NOT NULL,
    Phone NVARCHAR(20),
    Address NVARCHAR(255),
    Email NVARCHAR(100),
    PasswordHash NVARCHAR(255) NOT NULL,
    CreatedDate DATETIME DEFAULT GETDATE(),
    Note NVARCHAR(255)
);